### ISSUE TITLE
Unable to Update Item Quanity in Cart by Clicking on Add to Cart

### ISSUE THREAD

**Issue by mdwiltfong** [i-samuel/ecommerce-pern-app#1]
Steps to reproduce: 

1. Add a single quantity of an item to your cart. 
2. Check that the item is in your cart with one quantity.
3. Go back to the item. Simply click on Add to Cart.

Expectation: 
You should be able to add a single additional quantity of the item to the cart. Let's say the customer knows they added one item, but they wanted to add two. If they click on Add To cart while the quantity is set to one, the cart quantity in the cart should be incremented by one.
What's actually happening:
Instead of being able to increment the quantity in the cart, it looks like whatever quantity is set on the item page is updating the cart. This is not typical UX since the page sets up the expectation that you are adding X quantity to your cart. Instead the app is updating the cart based on what is in the quantity.

**Comment by i-samuel** [comment]
Hi,

I've addressed the issue you raised regarding Cart Update. The fix has been pushed to the repository, and the problem should now be resolved.

If you could check it out and let me know if everything works as expected, that would be great!

Thanks again for your feedback!
